// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Conntrack = NewAsset("conntrack.c", "21af6774dcd46b2431349f152fc9f117d586f95e43e1f99b0463af8868f644ea")
