// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Http = NewAsset("http.c", "cf0b3e4f4bbdffc5676ad7013d3f26a67e3a313271bb64d97e1146dc19da6462")
