// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Http = NewAsset("http.c", "2b3a1364eaf8f2566f2761bcb9871b63cfd0bb97b9f741d267cea3d95af390d0")
