// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = NewAsset("runtime-security.c", "47c355ecf20c8a7c1afdd43dccbfb50f5964362b6c152718d46909d72e0e1492")
