// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = NewAsset("runtime-security.c", "e6d3c6ff9fbd3fbb088571ca301a6a45d8e57924919d781538b5067374e5e169")
