// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Tracer = NewAsset("tracer.c", "b59c0f354c7bf9e5db9937c79e03e1d8448588bd96b0e578d21311664e92b328")
